"""empty message

Revision ID: 4bc3a1c15309
Revises: 69b10ec9fadf
Create Date: 2023-11-14 18:35:20.377225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bc3a1c15309'
down_revision = '69b10ec9fadf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('documento', sa.String(length=16), nullable=False),
    sa.Column('endereco', sa.String(length=50), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cliente')
    # ### end Alembic commands ###
