"""Inicialização

Revision ID: 69b10ec9fadf
Revises: 
Create Date: 2023-11-13 21:05:33.021574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69b10ec9fadf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('qtdQuartos', sa.Integer(), nullable=True),
    sa.Column('qtdBanheiros', sa.Integer(), nullable=True),
    sa.Column('rua', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('casa')
    # ### end Alembic commands ###
